// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Property struct {
	ID       string `json:"_id"`
	Price    int    `json:"price"`
	Location string `json:"location"`
	URL      string `json:"url"`
	Entered  string `json:"entered"`
	Views    int    `json:"views"`
	Type     string `json:"type"`
	DaftID   int    `json:"daft_id"`
	Bathroom int    `json:"bathroom"`
	Bed      int    `json:"bed"`
	Removed  string `json:"removed"`
}

type Stat struct {
	ID                string  `json:"_id"`
	Timestamp         string  `json:"timestamp"`
	PriceAverage      float64 `json:"price_average"`
	PriceHigh         float64 `json:"price_high"`
	PriceLow          float64 `json:"price_low"`
	PriceDistribution []int   `json:"price_distribution"`
}
