// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Property struct {
	ID       string `json:"id"`
	Price    int    `json:"price"`
	Location string `json:"location"`
	URL      string `json:"url"`
	DaftID   int    `json:"daftId"`
	Entered  string `json:"entered"`
	Views    int    `json:"views"`
	Type     string `json:"type"`
	Bathroom int    `json:"bathroom"`
	Bed      int    `json:"bed"`
}
